# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: US - Used by customers to monitor App Health from DNAS Dashboard.
    url: https://us-cisco-dna.rifiniti.com/production/health-check
  - name: EU - Used by customers to monitor App Health from DNAS Dashboard.
    url: https://eu-cisco-dna.rifiniti.com/production/health-check

  - name: US - Determines health of Customer data being pushed to us.
    url: https://backend-optimo-x-us-east-1-prod.rifiniti.com/cisco/dna/health-check-api
  - name: EU - Determines health of Customer data being pushed to us.
    url: https://backend-optimo-x-eu-central-1-prod.rifiniti.com/cisco/dna/health-check-api

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: FMS A - Cisco DNA Application status page.
  introTitle: Monitor the availability of the websites
  introMessage: This is a status page which uses **real-time** data from our endpoinds
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Cisco DNA
      href: https://www.dnaspaces.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
